<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
<link rel="stylesheet" href="gridstyle.css">
    <title></title>
  </head>
  <body>

<div class="grid">
<div class="timegrid">
  <div>Tid/dato</div>
  <div>8:00</div>
  <div>9:00</div>
  <div>10:00</div>
  <div>11:00</div>
  <div>12:00</div>
  <div>13:00</div>
  <div>14:00</div>
  <div>15:00</div>
  <div>16:00</div>
  <div>17:00</div>
  <div>18:00</div>
  <div>19:00</div>
  <div>20:00</div>
  <div>21:00</div>
</div>
  <div>Mandag
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
  </div>
  <div>Tirsdag
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
  </div>
  <div>Onsdag
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
  </div>
  <div>Torsdag
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
  </div>
  <div>Fredag
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
  </div>
  <div>Lørdag
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
  </div>
  <div>Søndag
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
    <div>empty</div>
  </div>
</div>

</body>
</html>
